name: CI/CD Examen

on: [push]

jobs:
  nombres:
    runs-on: ubuntu-latest
    steps:
      - name: 'Mi username'
        run: echo ${{ github.actor }}

      - name: repository
        uses: actions/checkout@v4

      - run: echo "the ${{ github.repository }}"

      - name: 'rama'
        run: echo ${{ github.ref }}

  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.repository_owner }}/examen-back:latest

  github-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/examen-back:latest